AVSS work in process mode
initc3/HoneyBadgerMPC pull request #291
Opened 2019-05-06 03:34 UTC by hybridNeo

AVSS works in process mode. Future changes will add flag for type of AVSS.

2019-05-06 04:59 UTC, smkuls requested changes

2019-05-06 04:59 UTC, smkuls commented on scripts/launch.sh
> +     splitw -v -p 50 "${CMD} -d -f ${CONFIG_PATH}.3.json; sh" \; \
This and the config change will break the other existing scripts. Can you create separate configs for AVSS? Can you also make this script generic by having default number of panes as 4 unless passed from the command line?

2019-05-06 04:59 UTC, smkuls commented on honeybadgermpc/protocols/avid.py
> +    async def disperse(self, sid, pid, input_list, client_mode=False):
Update the docstring to say what a client mode is.

Basically in the client mode, the dealer just sends the first message to all the receivers and returns.

2019-05-06 04:59 UTC, smkuls commented on honeybadgermpc/poly_commit_const.py
> +        alpha = ZR.random(0)
These shouldn't be by default hard coded. The seeds should be set from the command line.

2019-05-06 04:59 UTC, smkuls commented on honeybadgermpc/hbavss.py
> +def get_avss_params(n, t):
Do not duplicate code, modify the existing method to take a seed.

2019-05-06 04:59 UTC, smkuls commented on honeybadgermpc/hbavss.py
> +            # Dealer
You can remove this comment. The log makes it clear.

2019-05-06 04:59 UTC, smkuls commented on honeybadgermpc/hbavss.py
> +        crs = gen_pc_const_crs(t, g=g, h=h)
move this till `592` out of the `with`. Basically start with `HbAVSS` directly in the `with` (no need to unnecessarily setup network connection if we don't want to use them right away.

2019-05-06 04:59 UTC, smkuls commented on honeybadgermpc/hbavss.py
> +            await avid.disperse(tag, self.my_id, dispersal_msg_list, client_mode=True)
Update the comment to say, that the dealer will send the initial message and then can terminate.

2019-05-06 04:59 UTC, smkuls commented on honeybadgermpc/hbavss.py
> +logger.setLevel(logging.NOTSET)
Comment this again and change the `logger.info` in main to a print.

2019-05-06 19:59 UTC, chitianhao commented on honeybadgermpc/hbavss.py
> +        tag = f"{dealer_id}-{avss_id}-B-RBC"
Nice catch. I should have updated this.

2019-05-06 19:59 UTC, chitianhao commented on honeybadgermpc/protocols/avid.py
> +            if client_mode:
Add a comment for this.

2019-05-07 18:10 UTC, amiller commented
needs flake8 fix

2019-05-08 00:46 UTC, smkuls approved these changes

2019-05-08 00:50 UTC, smkuls commented on honeybadgermpc/hbavss_light.py
> +logger.setLevel(logging.NOTSET)
You don't need this and the two lines before this.

2019-05-08 00:52 UTC, merged

2019-05-08 00:54 UTC, smkuls reviewed
Can you open an issue so that we fix all the comments on this PR? This PR makes changes which can affect other protocols [hard coding the seed for polynomial commitments] and is also not in a great shape overall.

2019-05-08 00:54 UTC, smkuls commented on honeybadgermpc/hbavss_light.py
> +logger.setLevel(logging.NOTSET)
Same in the other file

2019-05-08 00:54 UTC, smkuls commented on honeybadgermpc/hbavss_batch.py
> +            logger.info(f"Dealer timestamp: {time.time()}")
You should use `%s` to log and not format strings