Adding a couple tutorial missions [not ready]
initc3/HoneyBadgerMPC pull request #333
Opened 2019-06-05 17:39 UTC by amiller

2019-06-07 07:33 UTC, amiller commented
The tutorial is nearly complete and includes a README to be self-contained

2019-06-07 22:01 UTC, sbellem requested changes
Both tutorial succeeded in the docker-compose based environment.

There's just the small typo for the instruction on running tutorial 2 that needs to be corrected.

2019-06-07 22:01 UTC, sbellem commented on apps/tutorial/README.md
> +scripts/launch-tmuxlocal.sh apps/tutorial/hbmpc-tutorial-2.py conf/local/mpc
the config option needs to be `conf/mpc/local` instead of `conf/local/mpc`

`scripts/launch-tmuxlocal.sh apps/tutorial/hbmpc-tutorial-2.py conf/mpc/local`

2019-06-08 15:00 UTC, amiller commented on apps/tutorial/README.md
> +scripts/launch-tmuxlocal.sh apps/tutorial/hbmpc-tutorial-2.py conf/local/mpc
ok

2019-06-08 15:46 UTC, merged