Add more useful traceback message
initc3/HoneyBadgerMPC pull request #403
Opened 2019-12-02 22:23 UTC by amiller

The logging tool in utils/misc.py prints an exception when one is encountered during a background task, such as mixin operations. However, this currently doesn't print the stack trace so there's not much info about the underlying exception

See for instance
https://github.com/amitgtx/HoneyBadgerMPC/commit/c0f6fc7c00e36cb0998882d0689df51d6d3ae051

This PR uses traceback.format_exception to provide a better error message.
Before:
```
2019-12-02 22:17:55,548:[misc.py:14]:[CRITICAL]: 
Exception: 
<Task finished coro=<AsyncMixin.__call__() done, defined at /usr/src/HoneyBadgerMPC/honeybadgermpc/progs/mixins/base.py:41> exception=AssertionError("Preprocessing underrun f<class 'honeybadgermpc.preprocessing.ShareBitsPreProcessing'>")> 
<class 'AssertionError'> 
Preprocessing underrun f<class 'honeybadgermpc.preprocessing.ShareBitsPreProcessing'>
```
After:
```
2019-12-02 22:21:16,195:[misc.py:14]:[CRITICAL]: 
Exception: 
<Task finished coro=<AsyncMixin.__call__() done, defined at /usr/src/HoneyBadgerMPC/honeybadgermpc/progs/mixins/base.py:41> exception=AssertionError()> 
Traceback (most recent call last):
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/progs/mixins/base.py", line 48, in __call__
    return await cls._prog(context, *args, **kwargs)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/progs/mixins/share_comparison.py", line 207, in _prog
    r_bits, c_bits = await LessThan._transform_comparison(context, a_share, b_share)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/progs/mixins/share_comparison.py", line 124, in _transform_comparison
    r_b, r_bits = context.preproc.get_share_bits(context)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/preprocessing.py", line 668, in get_share_bits
    return self._share_bits.get_value(context)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/preprocessing.py", line 101, in get_value
    to_return, used = self._get_value(context, key, *args, **kwargs)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/preprocessing.py", line 322, in _get_value
    assert self.count[key] >= 1
AssertionError
```

2019-12-02 23:02 UTC, sanket1729 commented
ACK modulo the formatting issues

2019-12-02 23:03 UTC, sanket1729 requested changes
ACK modulo CI checks. Black and flake8 stuff

2019-12-04 04:19 UTC, sbellem approved these changes

2019-12-05 15:28 UTC, amiller commented
@sanket1729 checks pass

2019-12-05 15:31 UTC, merged

2019-12-05 15:31 UTC, sanket1729 commented
Merging despite CodeCov red flag. Seems irrelevant to the PR